GenericPropertyJSON: {"name": "tatgetPos", "type": -1, "arraySize": 16, "arrayType": "Vector3", "children": [
    {"name": "Array", "type": -1, "arraySize": 16, "arrayType": "Vector3",
     "children": [{"name": "size", "type": 12, "val": 16}, {"name": "data", "type": 9,
                                                            "children": [{"name": "x", "type": 2, "val": 0.35},
                                                                         {"name": "y", "type": 2, "val": 1.1},
                                                                         {"name": "z", "type": 2, "val": 0.537}]},
                  {"name": "data", "type": 9, "children": [{"name": "x", "type": 2, "val": 0.323357821},
                                                           {"name": "y", "type": 2, "val": 1.23393929},
                                                           {"name": "z", "type": 2, "val": 0.537}]},
                  {"name": "data", "type": 9, "children": [{"name": "x", "type": 2, "val": 0.247487366},
                                                           {"name": "y", "type": 2, "val": 1.34748733},
                                                           {"name": "z", "type": 2, "val": 0.537}]},
                  {"name": "data", "type": 9, "children": [{"name": "x", "type": 2, "val": 0.133939192},
                                                           {"name": "y", "type": 2, "val": 1.42335784},
                                                           {"name": "z", "type": 2, "val": 0.537}]},
                  {"name": "data", "type": 9,
                   "children": [{"name": "x", "type": 2, "val": -1.52989852E-08}, {"name": "y", "type": 2, "val": 1.45},
                                {"name": "z", "type": 2, "val": 0.537}]}, {"name": "data", "type": 9, "children": [
             {"name": "x", "type": 2, "val": -0.133939192}, {"name": "y", "type": 2, "val": 1.42335784},
             {"name": "z", "type": 2, "val": 0.537}]}, {"name": "data", "type": 9,
                                                        "children": [{"name": "x", "type": 2, "val": -0.247487366},
                                                                     {"name": "y", "type": 2, "val": 1.34748733},
                                                                     {"name": "z", "type": 2, "val": 0.537}]},
                  {"name": "data", "type": 9, "children": [{"name": "x", "type": 2, "val": -0.323357821},
                                                           {"name": "y", "type": 2, "val": 1.23393929},
                                                           {"name": "z", "type": 2, "val": 0.537}]},
                  {"name": "data", "type": 9,
                   "children": [{"name": "x", "type": 2, "val": -0.35}, {"name": "y", "type": 2, "val": 1.1},
                                {"name": "z", "type": 2, "val": 0.537}]}, {"name": "data", "type": 9, "children": [
             {"name": "x", "type": 2, "val": -0.323357821}, {"name": "y", "type": 2, "val": 0.9660608},
             {"name": "z", "type": 2, "val": 0.537}]}, {"name": "data", "type": 9,
                                                        "children": [{"name": "x", "type": 2, "val": -0.247487381},
                                                                     {"name": "y", "type": 2, "val": 0.852512658},
                                                                     {"name": "z", "type": 2, "val": 0.537}]},
                  {"name": "data", "type": 9, "children": [{"name": "x", "type": 2, "val": -0.133939251},
                                                           {"name": "y", "type": 2, "val": 0.7766422},
                                                           {"name": "z", "type": 2, "val": 0.537}]},
                  {"name": "data", "type": 9,
                   "children": [{"name": "x", "type": 2, "val": 4.173708E-09}, {"name": "y", "type": 2, "val": 0.75},
                                {"name": "z", "type": 2, "val": 0.537}]}, {"name": "data", "type": 9, "children": [
             {"name": "x", "type": 2, "val": 0.133939266}, {"name": "y", "type": 2, "val": 0.7766422},
             {"name": "z", "type": 2, "val": 0.537}]}, {"name": "data", "type": 9,
                                                        "children": [{"name": "x", "type": 2, "val": 0.247487321},
                                                                     {"name": "y", "type": 2, "val": 0.8525126},
                                                                     {"name": "z", "type": 2, "val": 0.537}]},
                  {"name": "data", "type": 9,
                   "children": [{"name": "x", "type": 2, "val": 0.32335785}, {"name": "y", "type": 2, "val": 0.9660608},
                                {"name": "z", "type": 2, "val": 0.537}]}]}]}
